### ISSUE TITLE
Error when making tarball

### ISSUE THREAD

**Issue by r-gr** [edib-tool/docker-edib-tool#11]
I've been getting an error whenever I try to build a project with EDIB. The error occurs in the `make-tarball.mk` makefile, giving the following output.

    | cp -vfa --parents /lib64/ld-linux-x86-64.so.2 /stage/rootfs/
    | cp: can't stat '/lib64/ld-linux-x86-64.so.2': No such file or directory
    | make[2]: Leaving directory '/build'
    | make[1]: Leaving directory '/build'
    | make[2]: *** [edib/make-tarball.mk:46: /stage/rootfs/lib64/ld-linux-x86-64.so.2] Error 1
    | make[1]: *** [edib/edib.mk:20: /stage/tarballs/20170407_181737/appname-0.1.0.tar.gz] Error 2
    | make: *** [edib/Makefile:6: edib] Error 2
    ==> An error happened!
    ==> Reason: Artifact tarball not created! Check for any errors above.

The package is successfully built prior to this error so I believe this is a bug in this docker image. The error occurs on this line in [`make-tarball.mk`](https://github.com/edib-tool/docker-edib-tool/blob/master/edib/make-tarball.mk#L46):

        cp -vfa --parents $* $(ROOTFS)/

but I'm not sure how makefiles work or what list of files the `$*` is referring to so I haven't been able to find a fix.

I get the same error on both Arch Linux and macOS. Elixir 1.4.2, edib package version 0.10.0 which is using docker-edib-tool v1.6.0.

**Comment by sb8244** [comment]
This is also happening to me. Were you able to figure out the problem @r-gr ?

**Comment by r-gr** [comment]
@sb8244 Sadly not, I had to drop using this project because it was causing more issues than it was worth (every build failed with the error above.)

As far as I can tell, the devs have given up on it. Nothing against them, it was a great tool while it worked and I greatly appreciate the effort of the authors but I spent about 2 days debugging it when I could have spent a few hours learning about Dockerfiles and doing it manually instead.

The method I now use works much more reliably and when there are errors, it's far easier to understand and debug the problem from the shell output. I adapted this method from various blog posts I found online. I would provide attribution and links to the posts but I can't remember which ones they were.

I'll create a new project and outline the method below (doesn't have to be a new project of course.)
This example assumes you're working on a Phoenix project but if not, everything other than generating the Phoenix project will apply. The build steps also assume you have Docker installed. Installing it was a huge pain for me on macOS but very painless on linux—there's loads of resources available online for this.

    $ mix phoenix.new --no-brunch --no-ecto my_app
    ...
    $ cd my_app
    $ tree -FL 1
    .
    ├── README.md
    ├── config/
    ├── lib/
    ├── mix.exs
    ├── priv/
    ├── test/
    └── web/

In `mix.exs` you'll need to add `distillery` as a dependency.

```elixir
defp deps do
    [{:phoenix, "~> 1.2.4"},
     ...
     {:distillery, "~> 1.4"}]
end
```

Then create the `distillery` release config.

    $ mix release.config
    ...
    An example config file has been placed in rel/config.exs, review it,
    make edits as needed/desired, and then run `mix release` to build the release

Now this part is the method I found elsewhere and I may or may not have altered it much, I honestly can't remember.

Create a file at the root of your project named `Dockerfile.build` (you could name it anything but that name makes sense in this context.) Here I'm using [msaraiva/elixir-dev](https://hub.docker.com/r/msaraiva/elixir-dev/) which is a very minimal image for building Elixir applications but hasn't been updated for Elixir 1.4 so you can find many alternatives if you require 1.4.

```dockerfile
FROM msaraiva/elixir-dev

# upgrade all packages and install required packages
RUN apk --update upgrade && \
    apk add docker erlang-xmerl && \
    rm -rf /var/cache/apk/*

# copy project directory to /build in container
COPY . /build

# set mix env to production for bulding release
ENV MIX_ENV prod

# switch to the /build directory containing project files
WORKDIR /build

# build a relase with distillery
RUN mix deps.get --only prod
RUN mix compile
RUN echo y | mix release.clean --implode
RUN mix release

CMD ["/bin/sh"]
```

Then create a `Dockerfile` at the root of the project. Here I'm using another minimal Image [msaraiva/elixir](https://hub.docker.com/r/msaraiva/elixir/) which contains the bare minimum for a built release to run.

```dockerfile
FROM msaraiva/elixir

# set necessary environment variables
ENV PORT=8000 MIX_ENV=prod APP_NAME=my_app

# this will be the root directory in the built container in which the
# app is located. call it whatever you want.
WORKDIR /app

# this adds the release built in Dockerfile.build to the WORKDIR (/app) in this container
ADD _build/prod/rel/$APP_NAME .

# expose the port the app uses (defined above)
EXPOSE $PORT

CMD trap exit TERM; /app/bin/$APP_NAME foreground & wait
```

Your directory structure will look something like this:

    $ tree -FL 1
    .
    ├── Dockerfile
    ├── Dockerfile.build
    ├── README.md
    ├── _build/
    ├── config/
    ├── deps/
    ├── lib/
    ├── mix.exs
    ├── mix.lock
    ├── priv/
    ├── rel/
    ├── test/
    └── web/

Now you will use `Dockerfile.build` to build a release with distillery. The point of building it in this way means it has the same environment as the production container. You will first have to set up Docker and make sure it's running, then you can build the release:

    $ docker build -t buildhelper.my-app -f Dockerfile.build .
    ...
    $ docker run -v /var/run/docker.sock:/var/run/docker.sock buildhelper.my-app docker build -t my-app -f Dockerfile .
    ...

The `-v /var/run/docker.sock:/var/run/docker.sock` causes the Docker build container to use the system Docker to build the release image because apparently there are many issues with running Docker inside Docker.

If you run `$ docker images`, you'll see that the image built with this method (called `my-app` in this example) is a bit larger than those built by EDIB but the difference is about 20MB and EDIB is broken for me. I'm sure there are ways to reduce the image size further but I haven't got around to making these optimisations yet. Looking at the EDIB code might offer some clues as to further optimisations.

**Comment by sb8244** [comment]
This is seriously helpful @r-gr. I managed to get it working but  approached it a little differently, although very similarly for certain aspects. I'm thinking about throwing up a blog post about it because it was a serious headache to finally get working.

**Comment by r-gr** [comment]
@sb8244 Please do, I'd be very interested to see how you tackled it! Luckily for my project I'm at an early-ish state where I'm not locked into any particular methodology for building/deployment but I'm definitely not completely happy with the method I outlined above, it's just Good Enough for the moment :)

If/when you write that blog post, drop a link here!

**Comment by asaaki** [comment]
Can you confirm, that this issue still exists with the latest version(s)?

**Comment by asaaki** [comment]
No active development.
