### ISSUE TITLE
Assets in phoenix 1.3

### ISSUE THREAD

**Issue by DianaOlympos** [edib-tool/docker-edib-tool#12]
In phoenix 1.3, the assets and js got moved into `/assets`.
So the brunch config and the package.lock got moved here.

First step toward fixing this would be to add a `IN_ASSETS_DIR` instead of `IN_APP_DIR` to the brunch and npm calls. Easy enough. But we also need to catter with non 1.3 people.

I see two possible solutions : 

1. We provide different docker image, and users use the `--edib` flag. Not nice imho.
2. We create a new option/flag for `mix-edib` and we use that to switch between different build pipeline for assets. It also allows to extend the possible build tool and pipeline we support if people want `webpack` or whatever.

Thoughts ?

ping @asaaki

**Comment by asaaki** [comment]
Hm, I think we could try to be smart and automatically check for common locations.
So for 1.3 we test for configs in /assets and otherwise fallback to pre-1.3 behaviour. WDYT?

**Comment by DianaOlympos** [comment]
Still working on that one, but work got a bit crazy. I have found a couple other thing we can do.

I am exploring defining if we are on 1.3+ or under through mix.exs deps, but it take a bit of time.

**Comment by asaaki** [comment]
> Still working on that one, but work got a bit crazy.

Don't worry, no rush! 😊
