### ISSUE TITLE
rsync not parametrable

### ISSUE THREAD

**Issue by DianaOlympos** [edib-tool/docker-edib-tool#13]
Right now we are doing a rsync of everything in the container.

I had the need to tailor the things that get ignored (everything got dumped on root on that project) and it could also matter for umbrella apps. The simplest solution i found was to create a `.edibignore` file at the root and use it with ``--exclude-from` in rsync. But this mean the file _needs_ to be present.

It is not too much of a problem, as we can do that in the prerequisites of `mix-edib`.

Thoughts ?

**Comment by asaaki** [comment]
Sounds interesting.
Any thoughts/ideas around utilizing existing ignore files?

For the idea above: the existence check can be done right before rsyncing and adjusting the command line for it then; shouldn't be big of a deal I think.
