### ISSUE TITLE
How does this compare to the multi stage builds in Docker 1.17? 

### ISSUE THREAD

**Issue by seivan** [edib-tool/docker-edib-tool#17]
My guess is the purpose here is to remove unnecessary build tools in the final image. How does it compare to the multi stage build in the latest Docker that allows you specify stages thus making the final image smaller.

**Comment by asaaki** [comment]
I have not given the multi stage builds a try yet, but according to documentation this should be pretty similar to what EDIB achieves.

EDIB was initially created before multi stage feature was a thing.

For a more in-depth comparison I would spend some time with this feature and check if there are differences to each other.
