### ISSUE TITLE
artifact.cfg's IMAGE_SETTINGS invalid on Windows

### ISSUE THREAD

**Issue by msiemens** [edib-tool/docker-edib-tool#4]
When building an image using the mix task the setting `IMAGE_SETTINGS` that is generated for `artifact.cfg` is passed to the docker import command in [`mix-edib/lib/edib/build_config/image/builder.ex`](https://github.com/edib-tool/mix-edib/blob/b1336c1d794322b30f222f0203925e531e70e224/lib/edib/build_config/image/builder.ex#L36) which in turn is executed in the system shell. On Windows this results in a call like this:

```
$> gunzip -c c:/Users/markus/project/tarballs/20160502_160817/project-0.0.1.tar.gz | docker import --change 'CMD trap exit TERM; /app/bin/project foreground & wait' - local/project:0.0.1
open trap: Das System kann die angegebene Datei nicht finden.
stdout: Broken pipe

gunzip: Der Befehl "wait'" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

The problem is that Windows' `cmd.exe` doesn't escape content between single quotes. Thus it interprets the `&` as a command separator and tries to execute the part before it in the background and also call everything behind it as a command. This obviously fails.

The obvious fix would be to replace the single quotes in [edib/make-artifact.mk](https://github.com/edib-tool/docker-edib-tool/blob/decb88ecedd695be3d8fbeb9afaa2764b14c75fd/edib/make-artifact.mk) with double quotes. The code in question:

```
RELEASE_SETTINGS = --change 'CMD trap exit TERM; /app/bin/$(APP_NAME) foreground \& wait'
```

I would've already opened a PR, but I don't know single quotes were used there on purpose or if Make doesn't care about single vs. double quotes?

**Comment by msiemens** [comment]
Actually, after applying a workaround, I now get this error:

```
$> gunzip -c c:/Users/markus/Documents/Coding/web/kappa.pm/backend/tarballs/20160502_164906/kappa-0.0.1.tar.gz | docker import --change "CMD trap exit TERM; /app/bin/kappa foreground & wait" - local/kappa:0.0.1
| Error response from daemon: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
```

Seems like Windows messes up the pipe. On the other hand, leaving single quotes and wrapping the whole command in `sh -c "..."` in mix-ebid works fine.

**Comment by asaaki** [comment]
I'll try that and see how that will work out.
Thanks for investigating the issue. 
For Windows related stuff I need any help, since I'm not developing on this platform.

**Comment by msiemens** [comment]
Thanks! Regarding Windows: I'm happy to help whereever I can.

**Comment by asaaki** [comment]
I've released [mix-edib v0.6.2](https://github.com/edib-tool/mix-edib) which uses the `sh -c "…"` wrapping. You might want to try it.

**Comment by msiemens** [comment]
Works perfect, thank you! :)

**Comment by asaaki** [comment]
Thank you for the contribution. Happy building! 💖
