### ISSUE TITLE
Fails to build when hex version is out of date.

### ISSUE THREAD

**Issue by jemc** [edib-tool/docker-edib-tool#6]
When running `mix edib` for my project:

```
Will use EDIB tool v1.3.2
==> Packaging your app release into a docker image. Stay tuned!
| $> docker run --rm  -v "/home/jemc/1/code/hg/elixir-promenade:/source:ro" -v "/home/jemc/1/code/hg/elixir-promenade/tarballs:/stage/tarballs:rw"  edib/edib-tool:1.3.2
==> Creating artifact (might take a while) ...
| make -f edib/prerequisites.mk
| make[1]: Entering directory '/build'
| mix hex.info
| Hex:    0.12.1
| Elixir: 1.3.2
| OTP:    18.3.2
| Built with: Elixir 1.2.5 and OTP 18.3.3
| Registry file available (last updated: 2016-09-19 17:37:18)
| File size:   2922kB (compressed 957kb)
| Memory size: 7833kB
| Fetch time:  1385ms
| Load time:   38ms
| Packages #:  2813
| Versions #:  13196
| rsync -av \
|   --exclude=.git\
|   --exclude=.edib.log \
|   --exclude=_build \
|   --exclude=deps \
|   --exclude=node_modules \
|   --exclude=rel/A new Hex version is available (0.13.2), please update with `mix local.hex` promenade \
|   --exclude=tarballs \
|   /source/ /build/app
| /bin/sh: syntax error: unexpected "("
| make[1]: *** [edib/prerequisites.mk:11: /build/app] Error 2
| make: *** [edib/Makefile:9: prerequisites] Error 2
| make[1]: Leaving directory '/build'
==> An error happened!
==> Reason: Artifact tarball not created! Check for any errors above.
```

Note that `A new Hex version is available (0.13.2) ...` is being used as part of the `rsync` invocation, causing a `sh` syntax error.

**Comment by asaaki** [comment]
Erm, this is an really unfortunate issue. Will update the images soon. Sorry for any inconvenience.

**Comment by rowpsmo1859** [comment]
### EDIT

 @asaaki updated the images according to https://hub.docker.com/r/edib/edib-tool/tags/

I would check if the problem still persists before taking the below advice

---

@jemc In the meantime,

To get this to work locally, build the docker image chain starting at https://github.com/edib-tool/docker-elixir-dev

**Comment by jemc** [comment]
To work around it locally, I already cloned and made this change:

``` diff
diff --git a/edib/prerequisites.mk b/edib/prerequisites.mk
index caf9adf..021cb38 100644
--- a/edib/prerequisites.mk
+++ b/edib/prerequisites.mk
@@ -3,7 +3,7 @@ include edib/shared.mk
 SSH_KEYS_SRC  = $(HOME)/ssh
 SSH_KEYS_DEST = $(HOME)/.ssh

-all: hex-info move-app copy-ssh-keys
+all: local-hex hex-info move-app copy-ssh-keys

 move-app: $(APP_DIR)

@@ -26,5 +26,8 @@ $(SSH_KEYS_DEST):
                rsync -av --no-owner $(SSH_KEYS_SRC)/ $(SSH_KEYS_DEST); \
        fi

+local-hex:
+       mix local.hex
+
 hex-info:
        mix hex.info
```

Wasn't sure if a PR like that would be welcome though.

**Comment by rowpsmo1859** [comment]
Oh right, I forgot that hex is installed [in the elixir dev docker image](https://github.com/edib-tool/docker-elixir-dev/blob/19d09be2140e4c218207e3d21febf8a3c6545799/Dockerfile#L16)

**Comment by asaaki** [comment]
We can add such `hex` tool update step, of course. It should add just a few extra seconds to the build time, which is not heavy.

Not sure, how urgent this is, since hex doesn't update that often.
I just need to make sure to trigger a toolchain update shortly afterwards somehow (for manual updates).

WDYT?
